version: '3.9'

services:
  logs:
    image: twitter-bot/logs
    build: logs
    container_name: logs-api
    networks:
      - app_network
    ports:
      - "8080:8080"
    volumes:
      - ./logs/src:/usr/app/src:rw
      - ./logs/static:/usr/app/static:rw
    environment:
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DB_NAME=logs-db-dev
      - MONGO_CONTAINER_NAME=twitter-api-db
      - LOGS_APP_ID=twitter-bot
      - APP_PORT=8080
    command: "yarn run dev"
  
  mongo:
    image: mongo:latest
    container_name: twitter-api-db
    ports:
      - "27017:27017"
    networks:
      - app_network
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    command: "--quiet --logpath=/dev/null"
    volumes:
      - ./mongodata:/data/db:rw

networks:
  app_network: